# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Efeito Borboleta
tagline:             Em versão texto
url:                 https://efeito-borboleta.matm.xyz
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Manuel Tarouca
  url:               https://matm.xyz
  email:             manuel+eb@matm.xyz

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/manueltarouca/efeito-borboleta
